### ISSUE TITLE
App just checks twice a day

### ISSUE THREAD

**Issue by ars1614** [RadarCOVID/radar-covid-android#1]
In my opinion, the pooling should be faster. 15min?

**Comment by davtun** [comment]
Not a programmer, but maybe too many checks could drain the phone's battery way too fast?

**Comment by Groctel** [comment]
The phone load shouldn't be that much of an issue, but the database server would probably wear faster from the increased cheking frequency. That being said, twice a day seems low.

**Comment by nukeador** [comment]
Probably 12 hours is a good balance between fast notification and server load, how do other countries handle this notification cadence?

**Comment by ars1614** [comment]
I disagree. 12 hours is too few. Mine just checks at 7 and 19. The first I’m still at bed. The second one I am at home already. I have been able to be with loads of people in between and the application will say I am safe.

**Comment by davtun** [comment]
As a reference, the iOS version also seems to use those same periods of time for exposure checks, 06:00 - 08:00 and 18:00 - 20:00. 

Curiously enough, it seems that a few days ago there were 3 daily checks, one extra scheduled at 13:00 - 15:00. Don't know if that was unexpected behaviour or if there were 3 scheduled checks per day before.

**Comment by Arasthel** [comment]
I might be wrong or have misunderstood this discussion, but I believe those 'checks' are the times when the app uploads their data and checks it agains the ones already uploaded to check if you've been exposed, they are not checks for nearby devices. So I guess knowing if you've been exposed right before you go to work or once you've come back home seems logical.

I do agree that more frequent checks would be nice, though. Knowing at 10AM that you've been exposed in your commute a couple of hours before would allow you to warn everyone at work and go back home earlier to self-isolate.

**Comment by LeonAlvarez** [comment]
You should check https://github.com/DP-3T/documents , exposure check is not related to the upload frequency

**Comment by ars1614** [comment]
> I might be wrong or have misunderstood this discussion, but I believe those 'checks' are the times when the app uploads their data and checks it agains the ones already uploaded to check if you've been exposed, they are not checks for nearby devices. So I guess knowing if you've been exposed right before you go to work or once you've come back home seems logical.
> 
> I do agree that more frequent checks would be nice, though. Knowing at 10AM that you've been exposed in your commute a couple of hours before would allow you to warn everyone at work and go back home earlier to self-isolate.

If that's right, I'm wrong then. I thought they were the checks with other devices. A explanation from the developers will get us out of doubt

**Comment by arivero** [comment]
> Probably 12 hours is a good balance between fast notification and server load, how do other countries handle this notification cadence?

For server load, a randomization is always helpful, if the alternative is all the machines doing the notification check at the same time. It could be interesting to combine an average frequency of six hours plus a preference for wifi.

**Comment by CarlosGS** [comment]
Please @ars1614  clarify the issue title, or close it, to avoid confusion ;)

**Comment by ars1614** [comment]
> Please @ars1614 clarify the issue title, or close it, to avoid confusion ;)

Can you clarify us what kind of verifications are the ones inside "exposure notifications" menu from Google (in my case). Because I thought they were when the app checked the surroundings in search of possible infected people. Other user suggested maybe they are only the verification with the server.

**Comment by pantic79** [comment]
Guys, verifications inside "exposure notificacions" menu from Google appears when the Google API to calculate the exposition is called. Take into account that there is a 20 calls per day limit according to the Google Exposure Notification Framework API version DP-3T is using now (https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes, see legacy mode). Therefore, two temporal windows in a day are used to call the API ideally 10 times (maybe less than 10 depending on the keys delta) to not overcome this limit.
The new Google API version puts in place a 6 calls per day limitation but also allows to evaluates several days at once.

**Comment by pantic79** [comment]
I'm closing this thread now. Please, let me know if  you have additional questions about this matter or if something is not clear yet.

Thanks for contributing to get a better COVID tracing solution.
