### ISSUE TITLE
Error: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device (Android app)

### ISSUE THREAD

**Issue by pedrojfernandez** [RadarCOVID/radar-covid-android#11]
Hola! Hi!
As people seams to report in English, I will do the same :-)

When I run the app (debug version) in my devices (I have tested two), this message appears just when it tries to activate the connection with the Google API for exposure notifications. The complete text of the error message is:

Error: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39507), resolution=null, message=null}

But when I install the app downloaded from the PlayStore, it works with no error message.

I need to use an API KEY for google tools or something similar?

Thanks in advance :-)

**Comment by pedrojfernandez** [comment]
HI again, I have see in the logs my compiled app is not whilelisted by google to use the api, service_is=236.

This means that we can not make the application works?

Thanks!

**Comment by JuanjoSalvador** [comment]
It seems our debug versions won't work al all due to the Google's API whitelist. I'm getting the same errors.

**Comment by apozas** [comment]
Same here, when I try to compile the proRelease version. Answers [here](https://github.com/google/exposure-notifications-android/issues/8) seem to indicate that in order to work, our keys must be whitelisted, indeed

**Comment by JuanjoSalvador** [comment]
@apozas now the question is... can we whitelist our keys?

**Comment by pedrojfernandez** [comment]
Google In the Google Service API glosary states:

Allowlisted accounts
We have partnered with public health agencies for purposes of collaboration and testing of Exposure Notifications apps while they are in development. An allowlist grants specific permissions for these Google partners.

Nothing about how to request the inclusion in the whitelist. If any of you know how, please share :-)

**Comment by JuanjoSalvador** [comment]
It seems like we have to ask for a whitelisting for a company. I mean, Google partners, so, no solo devs.

**Comment by mcarro** [comment]
Not exactly - the snippet from the GAEN API doc reads "for _these_ Google partners". It refers to health agencies, not to any company  / partner: GAEN access is restricted to health agency-sponsored developments.

**Comment by JuanjoSalvador** [comment]
So, the fastest way will be if Minsait or other company/agency behind Radar COVID bring us a development API key. And I'm pretty sure that this will never be.

**Comment by iCesofT** [comment]
@mcarro got it. GAEN access is restricted to health agency-sponsored developments and there can only be one application per country.

We close this issue if you don't mind.
