### ISSUE TITLE
Data updating issue

### ISSUE THREAD

**Issue by JuanjoSalvador** [RadarCOVID/radar-covid-android#15]
I use the app everyday, but it doesn't update its own data since August 26th. I'm looking for a manual refreshing/updating button into the app in order to get the last data by myself. 

Would be possible?

**Comment by nukeador** [comment]
Is this maybe related with #2 ?

**Comment by JuanjoSalvador** [comment]
Yeah, but more like an issue it's a request.

**Comment by arivero** [comment]
And see also https://github.com/RadarCOVID/radar-covid-android/issues/1

**Comment by JuanjoSalvador** [comment]
Not related, I'm not asking for a faster pull but for the manual way. With the current limits (max 2 per day), because sometimes the data seems stuck into a past date without updating, and there isn't an intuitive way to fix that. You need to deactivate and activate the radar again.

So putting a "refresh data" button would be nice for users. Specially for those without enough knowledge, this app should be suitable for all, not an specific needed target.

**Comment by iCesofT** [comment]
Thanks for the comments.

Data updating depends on the device, power safe,... if you open the application, it should refresh the information.

We close the issue. If you have issues, please, reopen it. Thank you!
