### ISSUE TITLE
🔑 Congratulations and keep working and improving

### ISSUE THREAD

**Issue by pamartineza** [RadarCOVID/radar-covid-android#25]
This GitHub issue is just an excuse to express my gratitude to the developers of RadarCovid and to congratulate and encourage them to keep working and improving. Right after the code was released I read tons of rage/hate/shit on social networks and I came to this repo expecting the worst.

Nothing is further from reality, I'm really pleased to have found a full-fledged app developed using a modern language as Kotlin, written in ENGLISH!! (as any public project in the world should be written), using clean code patterns and even including some tests.

We can now start discussing about the libraries used, the way some logic or algorithms are implemented, if there are better or worse patterns, if code comments would be welcome in some places, if some old keys shouldn't have been included in the repo, if the code style should be changed, fixed, etc... but this is just room for improvement from a GOOD STARTING POINT.

I have been developing Android Apps for the last 10 years of my career and I know what is to work under not optimal conditions or environments, without proper resources, managers, timing or enough workforce. I guess developing an App for a Public Administration as a client with the goal of saving people lives in the midst of a pandemic situation doesn't fit in the definition of "optimal environment".

In addition making your work public and available to be scrutinized by thousands of eyes and receive criticism, many of the times without any positiveness and totally useless, is a huge mental and self-confidence toll to pay that nobody is prepared to.

So, again, let me say you in my name and I'm sure in the name of many more developers, thanks for your work and keep improving.

**Comment by Sefford** [comment]
Menudo hijo del Tío Bob, tienes una app del copón. De espagueti nada, tu estás clean code. Menudo RxJava tienes, hijo de Martin Fowler. 

Olvídate de refactorizar, potencia ese código tan espectacular que tienes, hijo de Alistair Cockburn. Qué p**a envidia me das! 

Cuida un poco la inyección de dependencias y tira de Kotlin 1.4 en el IDE. LiveData y ViewModels es lo que necesitas para terminar de ponerla del copón. 

Menudo hijo de Joel Spolsky eres, ya quisiera yo esa pedazo de app. C*******o, hijo de mil Jake Warthons, te invidio muchísimo. Insisto, cuida un poco la inyección de dependencias y machácate en Kotlin 1.4, con esa app puedes quedarte del copón, c*******o. 

Y a los que dicen que haces código de mierda ni p**o caso, son un hatajo de pintaJSONs insecto-palos que solo les gusta lamer PRDs. Tu, sin embargo, estás del copón, hijo del grandísimo Dave Thomas. Qué suerte tenéis algunos con los proyectos. 

Saludos y a darle fuerte, c********o.

**Comment by mathias21** [comment]
Sin desmerecer el esfuerzo de los trabajadores que han hecho esta app, pero no es que el autor/autores haya/n hecho esta app por amor al arte. Se ha licitado su desarrollo por un total de 330.537,52 euros. Por ese dinero es de esperar una calidad de código suficiente. Qué quiero decir con esto? pues que se puede valorar el trabajo, pero dar las gracias por algo que hemos pagado entre todos...

**Comment by catluc** [comment]
> Menudo hijo del Tío Bob, tienes una app del copón. De espagueti nada, tu estás clean code. Menudo RxJava tienes, hijo de Martin Fowler.
> 
> Olvídate de refactorizar, potencia ese código tan espectacular que tienes, hijo de Alistair Cockburn. Qué p**a envidia me das!
> 
> Cuida un poco la inyección de dependencias y tira de Kotlin 1.4 en el IDE. LiveData y ViewModels es lo que necesitas para terminar de ponerla del copón.
> 
> Menudo hijo de Joel Spolsky eres, ya quisiera yo esa pedazo de app. C---------o, hijo de mil Jake Warthons, te invidio muchísimo. Insisto, cuida un poco la inyección de dependencias y machácate en Kotlin 1.4, con esa app puedes quedarte del copón, c---------o.
> 
> Y a los que dicen que haces código de mierda ni p--o caso, son un hatajo de pintaJSONs insecto-palos que solo les gusta lamer PRDs. Tu, sin embargo, estás del copón, hijo del grandísimo Dave Thomas. Qué suerte tenéis algunos con los proyectos.
> 
> Saludos y a darle fuerte, c---------o.

Te han pagado para dejar ese comentario? ;);) jajajaja

**Comment by Sefford** [comment]
> Te han pagado para dejar ese comentario? ;);) jajajaja

Nada mejor para subir el ánimo que unas risas! :smile:

**Comment by iCesofT** [comment]
Gracias por los comentarios.

Cerramos la issue.
