### ISSUE TITLE
Rework of the whole UI?

### ISSUE THREAD

**Issue by Akrai** [RadarCOVID/radar-covid-android#26]
The currently used UI design is very different from the Android standards, and takes a lot of space and big bottom buttons (with small icons and a big empty space) to what could be done very cleanly and without differing from the usual UIs in android apps. Right now the app doesn't have to show almost anything at all, it is just a background running app with a few links for more info about procedures and so on, but i think it will probably be improved to show info about how to avoid the app being frozen in some kinds of ROMs (miui for example), and maybe some other features, and adding things to the current UI, in my opinion, would be counter productive for the non tech savvy people, as makes the UI very cluttered...
For example, currently if you browse to the second and third menu using the bottom buttons, it will show a short text that you would have to scroll... it is a very short text and you have to scroll it, and besides the inefficient space usage, scrolling is an action that, i think, it is not very intuitive to a lot of people, i have seen frequently people not realizing you can scroll an app to see the rest of the options for example

I would suggest doing a UI refactor now that the app is not used very widely (and so to not make people see the old and new UI, only the new one, to avoid confusions) and just make a very simple, typical material design UI, with the same bottom buttons and the same text that it has right now.

Maybe someone experienced in android programming could do it very quickly, i don't know 🤷‍♂️ (edit: misunderstanding explained below)

**Comment by Arraiz** [comment]
La seccióno pensatala de problemas esta para comentar problemas REALES o "issues" (lo pone en la pestaña) de la aplicación o hacer peticiones para nuevas características que hagan que la aplicación mejore. Este comentario (y muchos mas) no necesario y ademas esta escrito por alguien que tiene una gran falta de respeto a los desarrolladores y usuarios

**Comment by Akrai** [comment]
i just intended to propose an improvement to the interface, that's why i created this issue, as a proposal for improvement, i'm sorry if i offended somebody, i don't understand the offense there though

**Comment by ignasi35** [comment]
> i just intended to propose an improvement to the interface, that's why i created this issue, as a proposal for improvement, i'm sorry if i offended somebody, i don't understand the offense there though

@Akrai I understand you had good intentions but I'm afraid there are a few objective indicators on the wording of the issue that can lead to thinking differently. It is generally recommended to avoid subjective forms like:

* "it is just a background running app". Instead, you could use "The app currently has N visible pages"
* "Maybe someone experienced in android programming". I don't think the expertise of the authors is public so this sounds unnecessarily aggressive. 

The purpose of this app (and all the context around it) is delicate enough that people working on it probably did it under the highest stress they've ever experienced.

As much as I agree that having a UI that's compliant with latest Android guidelines, I think cosmetic issues and other non-functional requirements beyond data accuracy are lo priority.

My two cents.

**Comment by Akrai** [comment]
oh i see, with "Maybe someone experienced in android programming" i did not absolutely intended to express anything at all about the authors, i was just saying that, as the authors developed the current ui, this improvement, which is mostly cosmetic as you said, i don't think they would make this rework, i don't know, i just feel that as they get paid for launching this product, and as the current ui is completely functional for it's purpose, there is no reason for changing it as it is a waste of money for the company, that's just what i meant, absolutely zero offense about them or implying that they don't know enough about developing, if that's that anyone understood i'm sorry, i didn't meant it

what i meant is that as they would probably not do this, then this should be done by a third party, freely by himself, that's all, and to try to encourage to do it i just said that this rework would probably be quickly to be done by an experienced dev

i'm sorry for the misunderstanding

**Comment by jcawe** [comment]
> La seccion de problemas esta para comentar problemas REALES o "issues" (lo pone en la pestaña) de la aplicación o hacer peticiones para nuevas características que hagan que la aplicación mejore. Este comentario (y muchos mas) no es necesario y ademas esta escrito por alguien que tiene una gran falta de respeto a los desarrolladores y usuarios

Creo que deberías calmarte, todos estamos aquí para ayudar. Si ves cualquier aplicación en GitHub suele tener muchas issues abiertas con sugerencias y a veces con problemas que realmente no son problemas.

Entiendo tu respuesta debido a la críticas que ha tenido esta aplicación por parte de cierta parte del espectro político español, pero la verdad es que leyendo el comentario yo no he visto ninguna mala intención en él.

Keep calm and peace ☮️

**Comment by iCesofT** [comment]
Gracias por los comentarios. El aspecto UX/UI considerando mantener las versiones de iOS/Android lo más parecidas.

Si no tenéis inconveniente, cerramos la issue.
