### ISSUE TITLE
Private keys leaked

### ISSUE THREAD

**Issue by Groctel** [RadarCOVID/radar-covid-android#3]
Specifically these two:

![ripgrep private keys](https://i.imgur.com/ZuIzRSn.png)

**Comment by iCesofT** [comment]
Hi.

Thank you for the advice. Those private keys were used during pilot program at La Gomera. We already drop them from the repository.

Regards

**Comment by Groctel** [comment]
@iCesofT You may want to remove them from the git history: https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history

**Comment by ilopmar** [comment]
Agree, as long as you don't remove it from the history, anyone can see it and use it. That private key should also be revoked.

**Comment by javierprovecho** [comment]
More keys ...

https://github.com/search?l=YAML&q=org%3ARadarCOVID+PRIVATE&type=Code
