### ISSUE TITLE
¿Se permite abrir "issues" en español?

### ISSUE THREAD

**Issue by Danoloan10** [RadarCOVID/radar-covid-android#32]
🔑
Veo que toda la conversación se está realizando en inglés, pero no he visto ninguna regla en el fichero [CONTRIBUTING.md](https://github.com/RadarCOVID/radar-covid-android/blob/master/CONTRIBUTING.md) al respecto.

Supongo que en la discusión de una aplicación de origen español es esperable que sí se pueda hablar en español.

**Comment by pantic79** [comment]
Por supuesto, puedes hacerlo.
