### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by Yonseca** [RadarCOVID/radar-covid-android#33]
Hi, 

Today I found [this twit](https://twitter.com/VitorSuarez/status/1304728857451339776) from Víctor Suárez on Twitter requesting language support for Asturian. 

On the one hand, I found pull request #30, which seems to be translating the app to Galician. 
On the other hand, the same tweet cited above shows there's already support for Catalan and English. I think this is already being discussed in RadarCOVID/radar-covid-backend-configuration-server#4, but I still haven't found where are the translation strings located. 

Is it possible for us to translate the app into any other language? How could we do it? Is it OK to translate texts the same way as in #30?

Thanks.

**Comment by erral** [comment]
See #24 also.

**Comment by enolp** [comment]
See this too https://github.com/RadarCOVID/radar-covid-backend-configuration-server/issues/5

**Comment by Yonseca** [comment]
@enolp Thanks!

I'd like to believe that Contentful is being used as something common for both Android and iOS versions of RadarCovid. I really ignore how does it work; however it would be very nice if people had the oportunity to contribute (just like in any other open source project).  

It would be really sad to see that PRs like #24 or #30 are a waste of time. There must be a way.

**Comment by iCesofT** [comment]
Language support is served by configuration server and data is loaded from Contentful. We will check if we can provide a list with all the texts.
