### ISSUE TITLE
Notificación no útil.

### ISSUE THREAD

**Issue by FranAFV** [RadarCOVID/radar-covid-android#35]
Recibo desde hace unos días una  notificación recurrente: "Radar COVID No funciona correctamente. Error al cargar nuevos datos de infección".
Si la pulso sobre ella se abre la app y allí todo parece correcto, ninguna alerta aparece ni nada que indique como solventar el error que indicaba la notificación.

**Comment by JavierTobal** [comment]
Puedes comprobar la fecha de la actualización de datos que aparece en la ventana a la que llegas desde el cuadro "nivel de exposición". Si la fecha no está actualizada es que ha fallado algo, puedes desactivar y activar el Radar COVID para forzar la actualización.

**Comment by FranAFV** [comment]
Sinceramente, no creo que mi tío de 70 años sepa que tiene que actuar así ante ese tipo de notificación.

**Comment by JavierTobal** [comment]
Por supuesto. Esto es un fallo que tendrán que corregir los desarrolladores.

**Comment by avecina** [comment]
¿Tienes un Xiaomi con MIUI o un Huawei?

**Comment by daveruiz** [comment]
Puedo confirmar que lo he visto en un Xiaomi Redmi 5, mismos síntomas, una notificación pero en la aplicación no veo nada raro. En cambio el Galaxy S9 que tengo va perfecto.

**Comment by FranAFV** [comment]
> ¿Tienes un Xiaomi con MIUI o un Huawei?

El error se dio en un Motorola, con Android 8 y bastante limpio por parte de la marca.

Creo que el error se solucionó con los pasos de @JavierTobal. Aun así no fue algo inmediato, en el primer intento tras desactivar y activar radarcovid no se actualizaron los datos. Abandoné la app y cuando volví a las horas ya sí aparecía una fecha reciente con actualización correcta.

Per sigo pensando como al inicio de esta issues: tras la notificación debería haber alguna indicación con cómo corregir el error. Mucha de la población general seguro que no cae en la cuenta de que debe comprobar la fecha de última actualización y si no es reciente debe desactivar/activar y esperar.

**Comment by albertovecina** [comment]
¿Podrías especificar el modelo?

Gracias. Un saludo.

**Comment by ragovi** [comment]
Xiaomi Mi 10 Lite. Misma notificación, mismo error. Sólo se arregla si abro la app y desactivo y re-activo el servicio en la app. Si pasan varios días sin abrir la app, aunque esté corriendo en segundo plano, los datos no se actualizan. Casi un mes con esto, por favor subidle la prioridad a esta issue, ni siquiera está asignada

**Comment by pantic79** [comment]
Hola @ragovi ,

cuando abres la aplicación, ¿se te actualiza el listado de comprobación de exposiciones?. Por otro lado, a tu pregunta sobre si se pierden los contactos almacenados en el dispositivo cuando desactivas y activas el radar la respuesta es no, no se pierden.

Gracias por ayudarnos a mejorar la aplicación.

**Comment by ragovi** [comment]
Hola, por mi experiencia no, no se actualiza. Hasta que no desactivo y re-activo el servicio no se actualiza el listado a la fecha del día, ya lo he comprobado varias veces. Mañana lo vuelvo a probar.

**Comment by pantic79** [comment]
Hola,

por favor, ¿podrías probar la solución que se indica [aquí](https://github.com/RadarCOVID/radar-covid-android/issues/2)?.

Muchas Gracias!.

**Comment by ragovi** [comment]
El battery saver ya lo tenia configurado sin restricciones, me faltaba el auto-start. Lo probaré estos días y te digo si desaparece la notificación. Hoy NO ha salido, así que de momento tiene buena pinta

**Comment by pantic79** [comment]
Fenomenal!. Esperemos que evolucione bien.

Gracias por tu ayuda!

**Comment by iCesofT** [comment]
Hola. Se cierra tras haber seguido los pasos para ahorro de energía. @ragovi , por favor, si vuelves a tener problemas, reabre la issue. Muchas gracias por tu ayuda.

**Comment by ragovi** [comment]
Hola!

He estado liado, pero precisamente os iba a escribir sobre esto. He estado varios dias sin abrir la app, la última ves fue cuando escribí mi anterior post (como en Madrid aún no han integrado la app no le dot mucha importancia de momento). Precisamente  ayer dia 6 , a las 01:50 aprox, me dio por comprobar y volvio a salir la notificación, y pude comprobar que los datos no estaban actualizados desde el día 28 de septiembre, justo el tiempo que llevaba sin abrir la app. Así que algo sigue sin funcionar del todo bien. Hoy día 7 no ha salido.
![Screenshot_2020-10-06-01-52-33-107_es gob radarcovid](https://user-images.githubusercontent.com/2254771/95388022-d9412d80-08f1-11eb-9e47-64eca215c70c.jpg)
![Screenshot_2020-10-06-01-51-47-911_com google android gms](https://user-images.githubusercontent.com/2254771/95388025-da725a80-08f1-11eb-9452-24f15e12d3f0.jpg)
![Screenshot_2020-10-06-01-51-24-753_com google android gms](https://user-images.githubusercontent.com/2254771/95388026-db0af100-08f1-11eb-9e80-2bbdc2cf53d6.png)

**Comment by ragovi** [comment]
Por cierto @iCesofT no puedo reabrir porque yo no soy el creador, ni la he cerrado yo, ni soy colaborador del proyecto.

**Comment by iCesofT** [comment]
Gracias @ragovi. Reabro.

**Comment by iCesofT** [comment]
Tipo de dispositivo?

**Comment by ragovi** [comment]
Xiaomi Mi 10 Lite
![IMG_20201008_003208](https://user-images.githubusercontent.com/2254771/95394983-e2d09280-08fd-11eb-9d02-e4298d928d3f.jpg)

**Comment by ragovi** [comment]
Buenas, Desde la actualización del 8 de octubre no he vuelto a observar la incidencia, he comprobado cada 2/3 días. Por mi parte podéis cerrar el issue. Felicidades por el trabajo, y ánimo, a ver si conseguimos que mucha más gente empiece a usar la app.

**Comment by iCesofT** [comment]
Gracias @ragovi . Cerramos la issue. Seguimos en "contacto" :-)
