### ISSUE TITLE
It is not possible to change language

### ISSUE THREAD

**Issue by ilazgo** [RadarCOVID/radar-covid-android#37]
I have been with the Radar COVID installed for several weeks and today Galician translation was implemented. I updated the app but I cannot see the settings to change the language.

Do I have to uninstall and install again to select the language? If I do that all the tracking information will be lost, right?

**Comment by pantic79** [comment]
It's true. We are working on this for the next release.

**Comment by pantic79** [comment]
Hello,

this functionality is already available on released 1.1.0 application version.

Thanks.

**Comment by avecina** [comment]
Fixed in e6ef40c547d0171cb5e4cf9b227dd339a98672de
