### ISSUE TITLE
F-droid inclusion

### ISSUE THREAD

**Issue by JVAQUEROM** [RadarCOVID/radar-covid-android#38]
[F-droid](f-droid.org) is an alternative app store to Google Play Store which has only free open source apps. I would like to see Radar COVID on it, but they request that "the original app author has been notified (and supports the inclusion)." So I would like the author(s) to support such inclusion before requesting the inclusion to F-droid's team.

I just opened the issue for the request (in case Radar COVID authors support this), and got [this comment](https://gitlab.com/fdroid/rfp/-/issues/1497#note_415406957). It seems there are Firebase and GMS stuff that make it not free open source. So I hope this can be replaced by MicroG's implmentation of the exposure api, if possible.

Thank you

**Comment by aeri** [comment]
The new microG release has support for [Exposure Notifications](https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.12.203315), I have tested it and it seems to work well with Radar COVID, it could be very interesting the integration in F-droid.

**Comment by EchedeyLR** [comment]
@JVAQUEROM check https://github.com/RadarCOVID/radar-covid-android/issues/27#issuecomment-691392156

**Comment by JVAQUEROM** [comment]
I think the new Android version (1.0.7) has dropped Firebase dependency so I think inclusion in F-droid might be possible. Not sure about how the Google Exposure API dependency would be handled, but I can run the app without Google Services (with MicroG, being this a free dependency), so...

Just hope new version gets pushed to this repository soon.

**Comment by avecina** [comment]
We already can get to the desired target with the play store distribution. Thanks for your suggestion.

**Comment by JVAQUEROM** [comment]
Could you either support the inclusion in F-droid or at least provide an APK in the "release" section of github? I understand you reach your target with Google Play Store, but others could benefit from this action at a very small cost.

Thank you in advance.

**Comment by EchedeyLR** [comment]
@avecina could you reply to the last message from @JVAQUEROM

**Comment by p92canca** [comment]
> The new microG release has support for [Exposure Notifications](https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.12.203315), I have tested it and it seems to work well with Radar COVID, it could be very interesting the integration in F-droid.

Fantastic idea!!
