### ISSUE TITLE
Suggestion to use Weblate for translations

### ISSUE THREAD

**Issue by juanro49** [RadarCOVID/radar-covid-android#39]
Hi! The RadarCovid app is already translated into several regional languages, but as a suggestion to assist improving existing translations (or adding new ones) the Weblate platform could be used. https://hosted.weblate.org/

**Comment by pantic79** [comment]
Nice suggestion!. We are going to evaluate/consider this for future releases.

Thanks for your contribution.

**Comment by avecina** [comment]
The translations management is already resolved. Thanks for your time we'll review this suggestion in the future.
