### ISSUE TITLE
Private key in the public repository?

### ISSUE THREAD

**Issue by j-rivero** [RadarCOVID/radar-covid-android#4]
I just give a quick look into the code and found a [private key](https://github.com/RadarCOVID/radar-covid-android/blob/master/app/src/pre/res/raw/sedia_rsa_private_key.txt) hosted publicly in the repository? Is this expected or is it a mistake? I did not look carefully the design but just caught my attention as a possible bad development practice while I was browsing the code.

It would help to have the git history of the whole development to navigate to the commit that introduced it, unfortunately all was imported as a single commit making it impossible.

**Comment by nukeador** [comment]
#3

**Comment by j-rivero** [comment]
@groctel was faster than me, duplicate of #3.
