### ISSUE TITLE
La app aquí expuesta es la misma que la que está en Google Play?

### ISSUE THREAD

**Issue by tribore** [RadarCOVID/radar-covid-android#40]
Buenas.
He leído que la aplicación que se muestra aquí es distinta de la de Google Play. La verdad es que es lo único que me echa para atrás para descargármela.
Hoy he mirado en Google Play y he visto que se actualizó el 15 de septiembre. Yo no tengo ni puñetera idea de programación, así que pregunto a los entendidos que hayan diseccionado la versión de Google Play: ¿La versión de aquí y la de G Play ya son las mismas?

**Comment by jaitrum** [comment]
Vamos, yo creo que sí.. El fichero de changelog de master es del día 15 de Septiembre, y viene con los cambios que anuncia la app: 

https://github.com/RadarCOVID/radar-covid-android/blob/master/CHANGELOG.md

**Comment by j-rivero** [comment]
No tengo constancia de que haya existido confirnación por parte del equipo de desarrollo sobre que el código sea efectivamente el que termina en los stores pero las [dudas iniciales](https://github.com/RadarCOVID/radar-covid-android/issues/10) terminaron con la versión 1.0.6 que comentas.

**Comment by tribore** [comment]
> 
> 
> No tengo constancia de que haya existido confirnación por parte del equipo de desarrollo sobre que el código sea efectivamente el que termina en los stores pero las [dudas iniciales](https://github.com/RadarCOVID/radar-covid-android/issues/10) terminaron con la versión 1.0.6 que comentas.

He mirado el post que me has indicado y es suficiente argumento para mi.
Muchas gracias! ^^
