### ISSUE TITLE
Minimum versión API 21

### ISSUE THREAD

**Issue by Gorka7** [RadarCOVID/radar-covid-android#43]
Hi! 
I write it because I wanted to install the Covid Radar application on my "Amazfit Verge" smartwatch that has Android 5.0 with an Amazfit layer, that is, it is not pure Android, but it is impossible because I think that the minimum version that you have to have to install it is Android 6.0  and my smartwatch has 5.0 I have entered Android Studio I have to try the minimum version and it won't let me, I have knowledge of Android Studio but we are clear.  Could you lower the minimum version? 
Greetings.
Gorka.

**Comment by avecina** [comment]
Unafortunately the DP3T sdk still requieres the sdk 23. Thanks for your suggestion.
