### ISSUE TITLE
SDK 30 Location error notification

### ISSUE THREAD

**Issue by ponytojas** [RadarCOVID/radar-covid-android#44]
Starting in Android 11, localization is not necessary for the exposures api to work, as you can read in the following link.

https://blog.google/inside-google/company-announcements/update-exposure-notifications/

> On Android 11, which will soon be released, users will be able to use Exposure Notification apps without turning on the device location setting.

The App keeps sending an error notification if you try to use it without using the location (Even if bluetooth is on)

I attach a screenshot of the notification and the android version used
![IMAGE 2020-10-25 18:38:32](https://user-images.githubusercontent.com/17621785/97114564-876e1500-16f1-11eb-9dc9-188944037d54.jpg)
![IMAGE 2020-10-25 18:38:30](https://user-images.githubusercontent.com/17621785/97114566-8806ab80-16f1-11eb-9c3a-f591e1667a51.jpg)

It's a minor problem, but every now and then the notification keeps jumping and from what I can see it's something related to the app and not so much the API, although I may be wrong.

Thanks for your efforts and such a well done app

**Comment by wiyarmir** [comment]
It's fixed in release 1.0.5 of the DP-3T SDK https://github.com/DP-3T/dp3t-sdk-android/releases/tag/1.0.5

**Comment by ponytojas** [comment]
Yes support is added since the release you're pointing, but I'm only talking about the notification.

What I'm talking in this issue is the fact that even if the app is working properly without location, there's still a notification asking for it

**Comment by wiyarmir** [comment]
The notification is triggered by the SDK. Once they upgrade the SDK, it'll go away 〰️ .

**Comment by ponytojas** [comment]
The this issue can be closed.
Thanks for the explanation
