### ISSUE TITLE
Question: Why location permission is not in AndroidManifest.xml?

### ISSUE THREAD

**Issue by marcosflobo** [RadarCOVID/radar-covid-android#45]
Hi people,

I have a question. I see that, if I disable the location in my Android device, the RadarCovid raises a notification, demanding to re-enable the location on my device, for making RadarCovid working properly.

Why that requirement (location enabled) is not set on the AndroidManifest? (https://github.com/RadarCOVID/radar-covid-android/blob/develop/app/src/main/AndroidManifest.xml)

Thanks!

/question

**Comment by pantic79** [comment]
Hello,

check [this](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#architecture).

> Bluetooth functionality happens within on-device Google Play services. Bluetooth functionality includes all broadcasts and scans for BLE beacons, along with local database storage. Your app must have the BLUETOOTH and INTERNET permission in its manifest, but your app doesn't require and can't include ACCESS_COARSE_LOCATION, ACCESS_FINE_LOCATION, nor BLUETOOTH_ADMIN.

Thanks.

**Comment by marcosflobo** [comment]
Thanks @pantic79 for the answer. So, if I understood correctly, Android platform does not allow having ACCESS_COARSE_LOCATION nor ACCESS_FINE_LOCATION in the AndroidManifest.xml if you already have BLUETOOTH and INTERNET permission. That's why RadarCovid requests the location by its own.

Did I understand correctly?

**Comment by pantic79** [comment]
Actually I think it's a restriction for COVID applications. Probably if you include those permissions in the manifest file then the application won't get the approval for the Play Store distribution.

Thanks.

**Comment by marcosflobo** [comment]
A bit weird and not logical for my understanding. I close this question.

Thanks @pantic79 !
