### ISSUE TITLE
Funcionamiento hasta aceptar condiciones de uso

### ISSUE THREAD

**Issue by Yonseca** [RadarCOVID/radar-covid-android#46]
Hola, 

Hoy de casualidad he entrado en la aplicación y me ha aparecido un aviso para aceptar las condiciones de uso y la política de privacidad. Según pone, para usar RadarCOVID tengo que aceptarlas, pero no me ha saltado ninguna notificación al respecto.

Hará como una semana o dos que no entro a la aplicación. ¿Ha estado la app sin funcionar todo este tiempo?

Mi móvil es un Xiaomi Redmi Note 7. 

Gracias. 

![imagen](https://user-images.githubusercontent.com/6277518/97802634-0c52b480-1c45-11eb-811c-203ff89781fd.png)

**Comment by pantic79** [comment]
No, no ha dejado de funcionara. Es una funcionalidad que se ha incluido en la nueva release (1.1.0) que se te habrá actualizado. las condiciones de uso y políticas de privacidad han cambiado por la inclusión de la interoperabilidad europea y ese es el motivo por el que te aparece este recordatorio, con objeto de que puedas revisarlas y aceptarlas.

Gracias.
