### ISSUE TITLE
Change synthetics to viewbinding

### ISSUE THREAD

**Issue by rulogarcillan** [RadarCOVID/radar-covid-android#5]
The use of synthetics can throw exceptions, I would recommend changing to viewbinding in all views.

![rMbGU](https://user-images.githubusercontent.com/4234249/92622370-3d59dd00-f2c5-11ea-9463-01d5f1663b8d.png)

**Comment by erikmon** [comment]
https://github.com/RadarCOVID/radar-covid-android/pull/29

**Comment by seth0027** [comment]
@rulogarcillan @erikmon  Let me handle this issue?

**Comment by avecina** [comment]
Kotlin synthetics is an official and totally functional feature and works properly in this project. We appreciate the contribution and we understand the benefits but we are going to go with the simplicity and readability of kotlin synthetics.
