### ISSUE TITLE
Curly braces should be used on conditionals

### ISSUE THREAD

**Issue by josealfonsomora** [RadarCOVID/radar-covid-android#8]
🔑
From Kotlin code convention: https://kotlinlang.org/docs/reference/control-flow.html

```// Traditional usage 
var max = a 
if (a < b) max = b

// With else 
var max: Int
if (a > b) {
    max = a
} else {
    max = b
}
 
// As expression 
val max = if (a > b) a else b
```

There are a few places where the curly braces are omitted

**Comment by javichaques** [comment]
It is also possible to use the **maxOf** function
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.comparisons/max-of.html

**Comment by seth0027** [comment]
can I resolve this issue?

**Comment by avecina** [comment]
This is a coding style decision and this contribution is not affecting the code readability in an objective way. Thanks for your suggestion.
