### ISSUE TITLE
Private key in your repository is still accesible even after you removed it with a new commit

### ISSUE THREAD

**Issue by jiwidi** [RadarCOVID/radar-covid-android#9]
Hi!

So git is a wonderful tool, it allows you to keep track of file changes and facilitate coding with other people while keeping and structure code source. This means that your mistake of including a private key is still visible here https://github.com/RadarCOVID/radar-covid-android/blob/67a4506cc43a20062e87aebd5caa6be2ea0f6482/app/src/pre/res/raw/sedia_rsa_private_key.txt

@fjahijado If you push a new commit removing the key this won't fix your vulnerability, you have to remove all changes made to that file in previous commits (or remove the commits).

You can follow github official documentation [here](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository) to fix it

Any key that you published should be rotated as they have been compromised

:)

**Comment by albertfdp** [comment]
It does not really matter at this point. Any key that was commited at any point, must be considered compromised and a key rotation should be carried.

**Comment by jiwidi** [comment]
> It does not really matter at this point. Any key that has been commited, must be considered compromised and a key rotation should be carried.

Can't agree more

**Comment by itsjavi** [comment]
I hope that at this point all compromised private keys have been replaced @iCesofT

**Comment by NiciusB** [comment]
Obviamente son llaves que llevan tiempo fuera de uso. Y estaban públicas en la propia apk, mucho antes de en este repo

**Comment by alfonsoeromero** [comment]
:facepalm:

**Comment by arivero** [comment]
Alguien tendría que recomendar un manual sobre como reconstruir historias. Supongo que cuando haya un siguiente commit podran ejecutar un **git filter branch**

**Comment by fooock** [comment]
duplicate of #3 and #4, both closed. Why open another one again?

**Comment by albertfdp** [comment]
There are plenty of forks out there already (https://github.com/RadarCOVID/radar-covid-android/network/members) plus anyone might have done a copy of the keys already. There is absolutely no benefit on rewriting history as people suggest, the only solution is revoking the keys and generating new ones.

**Comment by spanishkangaroo** [comment]
> > It does not really matter at this point. Any key that has been commited, must be considered compromised and a key rotation should be carried.
> 
> Can't agree more

Unless they were just used in the past for testing and unusable now ; ) Check [this commit](https://github.com/RadarCOVID/radar-covid-android/commit/2eeab393aff5d62c91e10a184149d9c535d129de) and some other comments from @iCesofT.

**Comment by manueldevjour** [comment]
> Tienen toda la pinta de ser llaves que llevan tiempo fuera de uso. Y es probable que estuvieran públicas en la propia apk (por ser el dir /res), mucho antes de en este repo.
> 
> De cualquier modo, son llaves a qué? No tengo ni idea, pero imagino que serían para firmar las builds de test de La Gomera, lo cual las hace inútiles anyway.

Exactamente, es eso. Lo que se ha "comprometido" no está en uso desde las pruebas que se hicieron para La Gomera, es decir, que NO pasa nada. 

https://twitter.com/fjahijado/status/1303719651571097600

**Comment by iCesofT** [comment]
It's not used anymore as we said before.
